# Generated by Django 2.0.7 on 2019-09-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
