# Generated by Django 2.0.7 on 2019-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20190923_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='id',
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionA',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionB',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
